---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami
  name: whoami
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: whoami
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}

  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - image: traefik/whoami
          name: whoami
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
          env:
            - name: WHOAMI_NAME
              value: {{ .Values.name }}
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 20
            httpGet:
              path: /health
              port: http
